Repository OhEng-solux/developer, pull requests merged in 2025-08, with the labels that each got.

#113 [FEAT] fixing bugs
  Assets/Item/Key.asset
  Assets/Scenes/Day1.unity
  Assets/Scenes/Day2.unity
  Assets/Scenes/Day3.unity
  Assets/Scenes/Day4.unity
  Assets/Scenes/Day5.unity
  Assets/Scenes/Day6.unity
  Assets/Script/ImagePopupManager.cs
  Assets/Script/LightTrigger.cs
  Assets/Script/Menu.cs
  Assets/Script/PlayerManager.cs
  Assets/Script/PopupManager.cs
  Assets/Script/SaveManager.cs
  Assets/Script/TestChoice.cs
  Assets/Script/TransferScene.cs
Labels: FEAT, 성하🐱

#116 [FEAT] ItemUse in ChaseMode
  Assets/.DS_Store
  Assets/Item/Candy.asset
  Assets/Item/Hidden_Rule.asset
  Assets/Item/Kitchen_Rule.asset
  Assets/Item/Salt.asset
  Assets/Item/Use Candy.asset
  Assets/Item/Use Candy.asset.meta
  Assets/Item/Use Salt.asset
  Assets/Item/Use Salt.asset.meta
  Assets/Scenes/Day6.unity
  Assets/Script/.DS_Store
  Assets/Script/Inventory/.DS_Store
  Assets/Script/Inventory/CandyUse.cs
  Assets/Script/Inventory/CandyUse.cs.meta
  Assets/Script/Inventory/CandyUseManager.cs
  Assets/Script/Inventory/CandyUseManager.cs.meta
  Assets/Script/Inventory/InventoryManager.cs
  Assets/Script/Inventory/ItemViewer.cs
  Assets/Script/Inventory/ItemViewer.cs.meta
  Assets/Script/Inventory/KeyUse.cs
  Assets/Script/Inventory/SaltUse.cs
  Assets/Script/Inventory/SaltUse.cs.meta
  Assets/Script/Inventory/SaltUseManager.cs
  Assets/Script/Inventory/SaltUseManager.cs.meta
  Assets/Script/LightController.cs
  Assets/Script/LightTrigger.cs
  Assets/Script/NumberSystem.cs
  Assets/Script/PlayerManager.cs
  Assets/Script/PopupManager.cs
  Assets/Script/TaejuChase.cs
Labels: FEAT, 지윤🐨

#122 Remove Clue Replay Feature After Load
  Assets/Scenes/Day1.unity
  Assets/Scenes/Day2.unity
  Assets/Scenes/Day3.unity
  Assets/Scenes/Day4.unity
  Assets/Scenes/Day5.unity
  Assets/Scenes/Day6.unity
  Assets/Scenes/Ending_Bad.unity
  Assets/Scenes/Prologue.unity
  Assets/Scenes/Start.unity
  Assets/Script/Bound.cs
  Assets/Script/ClueTrigger.cs
  Assets/Script/ClueTrigger.cs.meta
  Assets/Script/SaveNLoad.cs
  Assets/Tiled/Lobby/lb_fun/lobby_object.png.meta
Labels: BUG, 채은🐶

#127 [BUG] Fix Ending BG & SE
  .DS_Store
  Assets/.DS_Store
  Assets/Scenes/Day1.unity
  Assets/Scenes/Day2.unity
  Assets/Scenes/Day3.unity
  Assets/Scenes/Day4.unity
  Assets/Scenes/Day5.unity
  Assets/Scenes/Day6.unity
  Assets/Scenes/Ending_True.unity
  Assets/Scenes/Start.unity
  Assets/Script/PlayerManager.cs
  Assets/Script/SaveManager.cs
  Assets/Sounds/.DS_Store
  Assets/Sounds/Effect/.DS_Store
Labels: BUG, 지윤🐨
