Repository OhEng-solux/developer, pull requests merged in 2025-07, with the labels that each got.

#8 feat: 맵 페이드 & 플래시 설정
  Assets/Resources/FX - Black.png
  Assets/Resources/FX - Black.png.meta
  Assets/Resources/FX - White.png
  Assets/Resources/FX - White.png.meta
  Assets/Scenes/1stfloor.unity
  Assets/Script/CameraManager.cs
  Assets/Script/FadeManager.cs
  Assets/Script/FadeManager.cs.meta
  Assets/Script/OrderManager.cs
  Assets/Script/OrderManager.cs.meta
  Assets/Script/PlayerManager.cs
  Assets/Script/TransferMap.cs
  Assets/UI Toolkit.meta
  Assets/UI Toolkit/PanelSettings.asset
  Assets/UI Toolkit/PanelSettings.asset.meta
  Assets/UI Toolkit/UnityThemes.meta
  Assets/UI Toolkit/UnityThemes/UnityDefaultRuntimeTheme.tss
  Assets/UI Toolkit/UnityThemes/UnityDefaultRuntimeTheme.tss.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/TagManager.asset
Labels: FEAT

#16 feat: 맵 이동 제한
  Assets/Scenes/1stfloor.unity
  Assets/Script/Bound.cs
  Assets/Script/Bound.cs.meta
  Assets/Script/CameraManager.cs
  Assets/Script/MovingObject.cs
  Assets/Script/TransferMap.cs
  Assets/player_pixel.PNG.meta
  ProjectSettings/TagManager.asset
Labels: FEAT, 채은🐶

#26 feat: 맵 이동 업데이트 & 맵 경계 설정
  Assets/Scenes/1stfloor.unity
Labels: FEAT, 채은🐶

#35 [FEAT] Map Wall Modify & Create passage
  Assets/Scenes/1stfloor.unity
Labels: FEAT, 성하🐱

#59 [FEAT] Day2 Modify
  Assets/Animation/Character/Yoonji/yoonji_sprite_0.controller
  Assets/Animation/UI/Start.controller
  Assets/Animation/UI/Start.controller.meta
  Assets/Animation/UI/StartBackground.controller
  Assets/Animation/UI/StartBackground.controller.meta
  Assets/Animation/UI/Start_Appear.anim
  Assets/Animation/UI/Start_Appear.anim.meta
  Assets/Animation/UI/Start_Disappear.anim
  Assets/Animation/UI/Start_Disappear.anim.meta
  Assets/Image/Sprite/chat_box (1).png
  Assets/Image/Sprite/chat_box (1).png.meta
  Assets/Image/Sprite/chat_box 1.png
  Assets/Resources/fifth_day.png
  Assets/Resources/fifth_day.png.meta
  Assets/Resources/first_day.png
  Assets/Resources/first_day.png.meta
  Assets/Resources/fourth_day.png
  Assets/Resources/fourth_day.png.meta
  Assets/Resources/second_day.png
  Assets/Resources/second_day.png.meta
  Assets/Resources/sixth_day.png
  Assets/Resources/sixth_day.png.meta
  Assets/Resources/third_day.png
  Assets/Resources/third_day.png.meta
  Assets/Scenes/Day1.unity
  Assets/Scenes/Day2.unity
  Assets/Scenes/Day3.unity
  Assets/Script/DayStart.cs
  Assets/Script/DayStart.cs.meta
  Assets/Script/DialogueManager.cs
  Assets/Script/ExitChecker.cs
  Assets/Script/MemoUIManager.cs
  Assets/Script/MemoUIManager.cs.meta
  Assets/Script/NPCPathMover.cs
Labels: FEAT, 성하🐱

#82 [FEAT] Inventory Update + Item Acquire
  .DS_Store
  .gitignore
  Assets/.DS_Store
  Assets/Image/UI/.DS_Store
  Assets/Image/UI/box_inventory_main.png
  Assets/Image/UI/box_system.png
  Assets/Image/UI/box_system.png.meta
  Assets/Image/UI/box_system_no.png
  Assets/Image/UI/box_system_no.png.meta
  Assets/Image/UI/box_system_yes.png
  Assets/Image/UI/box_system_yes.png.meta
  Assets/Image/UI/item.meta
  Assets/Image/UI/item/item_candy_false.png
  Assets/Image/UI/item/item_candy_false.png.meta
  Assets/Image/UI/item/item_candy_true.png
  Assets/Image/UI/item/item_candy_true.png.meta
  Assets/Image/UI/item/item_key_false.png
  Assets/Image/UI/item/item_key_false.png.meta
  Assets/Image/UI/item/item_key_true.png
  Assets/Image/UI/item/item_key_true.png.meta
  Assets/Image/UI/item/item_rulepaper_false.png
  Assets/Image/UI/item/item_rulepaper_false.png.meta
  Assets/Image/UI/item/item_rulepaper_true.png
  Assets/Image/UI/item/item_rulepaper_true.png.meta
  Assets/Image/UI/item/item_salt_false.png
  Assets/Image/UI/item/item_salt_false.png.meta
  Assets/Image/UI/item/item_salt_true.png
  Assets/Image/UI/item/item_salt_true.png.meta
  Assets/Image/UI/map_img.png
  Assets/Image/UI/map_img.png.meta
  Assets/Image/UI/ui_confirm.png
  Assets/Image/UI/ui_confirm_whiteO.png
  Assets/Image/UI/ui_confirm_whiteO.png.meta
  Assets/Item/Candy.asset
  Assets/Item/Hidden_Rule.asset
  Assets/Item/Key.asset
  Assets/Item/Kitchen_Rule.asset
  Assets/Item/Salt.asset
  Assets/Scenes/Day1.unity
  Assets/Scenes/Day2.unity
  Assets/Scenes/Day3.unity
  Assets/Scenes/Day4.unity
  Assets/Scenes/Day5.unity
  Assets/Scenes/Day6.unity
  Assets/Script/HiddenNoteEvent.cs
  Assets/Script/InventoryManager.cs
  Assets/Script/InventorySlot.cs
  Assets/Script/Item.cs
  Assets/Script/PuzzleManager.cs
  Assets/Script/TestChoice.cs
  Assets/Script/TestNumber.cs
Labels: FEAT, 지윤🐨

#88 [FEAT] Modify Day3 MiniGame
  .DS_Store
  Assets/.DS_Store
  Assets/Image/UI/box_save_main.png.meta
  Assets/Image/UI/box_save_off.png.meta
  Assets/Item/Hidden_Rule.asset
  Assets/Item/Key.asset
  Assets/Item/Kitchen_Rule.asset
  Assets/Scenes/Day3.unity
  Assets/Script/HiddenNoteEvent.cs
  Assets/Script/InventoryManager.cs
  Assets/Script/NumberSystem.cs
  Assets/Script/TestNumber.cs
Labels: FEAT, 지윤🐨

#110 [FEAT] Update Day3 Minigame Design & UseItem Logic
  .DS_Store
  Assets/.DS_Store
  Assets/Image/.DS_Store
  Assets/Image/UI/day3_drawer_false_img.PNG
  Assets/Image/UI/day3_drawer_false_img.PNG.meta
  Assets/Image/UI/day3_drawer_img.PNG
  Assets/Image/UI/day3_drawer_img.PNG.meta
  Assets/Image/UI/day3_drawer_true_img.PNG
  Assets/Image/UI/day3_drawer_true_img.PNG.meta
  Assets/Item/.DS_Store
  Assets/Item/Candy.asset
  Assets/Item/Hidden_Rule.asset
  Assets/Item/Key.asset
  Assets/Item/Kitchen_Rule.asset
  Assets/Item/Salt.asset
  Assets/Item/Use Hidden_Rule.asset
  Assets/Item/Use Hidden_Rule.asset.meta
  Assets/Item/Use Key.asset
  Assets/Item/Use Key.asset.meta
  Assets/Scenes/Day3.unity
  Assets/Scenes/Day4.unity
  Assets/Scenes/Day5.unity
  Assets/Scenes/Day6.unity
  Assets/Script/.DS_Store
  Assets/Script/HiddenNoteEvent.cs
  Assets/Script/Inventory.meta
  Assets/Script/Inventory/HiddenRuleUse.cs
  Assets/Script/Inventory/HiddenRuleUse.cs.meta
  Assets/Script/Inventory/HiddenRuleUseManager.cs
  Assets/Script/Inventory/HiddenRuleUseManager.cs.meta
  Assets/Script/Inventory/InventoryManager.cs
  Assets/Script/Inventory/InventoryManager.cs.meta
  Assets/Script/Inventory/InventorySlot.cs
  Assets/Script/Inventory/InventorySlot.cs.meta
  Assets/Script/Inventory/Item.cs
  Assets/Script/Inventory/Item.cs.meta
  Assets/Script/Inventory/ItemUseHandler.cs
  Assets/Script/Inventory/ItemUseHandler.cs.meta
  Assets/Script/Inventory/KeyUse.cs
  Assets/Script/Inventory/KeyUse.cs.meta
  Assets/Script/Inventory/KeyUseManager.cs
  Assets/Script/Inventory/KeyUseManager.cs.meta
  Assets/Script/NumberSystem.cs
  Assets/Script/PuzzleManager.cs
  Assets/Script/TestNumber.cs
  Assets/Tiled/.DS_Store
  Assets/Tiled/Kitchen/.DS_Store
  Assets/Tiled/Kitchen/kc_fun/cook_object 2.PNG
  Assets/Tiled/Kitchen/kc_fun/cook_object 2.PNG.meta
  Assets/Tiled/Kitchen/kc_fun/cook_object_7.asset
  Assets/Tiled/Kitchen/kc_fun/cook_object_7.asset.meta
  Assets/Tiled/Kitchen/kc_fun/cook_object_8.asset
  Assets/Tiled/Kitchen/kc_fun/cook_object_8.asset.meta
  Assets/Tiled/Kitchen/kc_fun/kc_fun.prefab
Labels: FEAT, 지윤🐨
